### ISSUE TITLE
2.0 release breaking chagnes checklist

### ISSUE THREAD

**Issue by jappeace** [snoyberg/keter#243]
Here I list a bunch of breaking make:

+ [x] get rid of data-default dependency entierly
       instead they should be normal functions. (so def + instance head, eg `defKeterConfig :: KeterConfig`)
 + [x] Types should be renamed to anything but types, like config instead.
 + [x] https://github.com/snoyberg/keter/issues/240
 + [x] Get rid of re-exports in types
 
---

For now I don't think `2.0` should /not/ reduce the feature set.
But if someone uses it as a library I think it could cause some build errors.
